---

test_task:
  alias: "build_and_test"
  name: "Build and Test"
  container:
    image: docker.io/library/rust
  install_script: cargo build
  test_script:
    - cargo-clippy
    - cargo test

success_task:
  name: "Total success"
  depends_on:
    - "build_and_test"
  clone_script: /bin/true
  script: /bin/true
  container: 
    image: docker.io/library/alpine
