---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

downstream_package_name: netavark
upstream_tag_template: v{version}

# These files get synced from upstream to downstream (Fedora / CentOS Stream) on every
# propose-downstream job. This is done so tests maintained upstream can be run
# downstream in Zuul CI and Bodhi.
# Ref: https://packit.dev/docs/configuration#files_to_sync
files_to_sync:
  - src: rpm/gating.yaml
    dest: gating.yaml
    delete: true
  - src: plans/
    dest: plans/
    delete: true
    mkpath: true
  - src: test/tmt
    dest: test/tmt
    delete: true
    mkpath: true
  - src: test-dhcp/tmt
    dest: test-dhcp/tmt
    delete: true
    mkpath: true
  - src: .fmf/
    dest: .fmf/
    delete: true
  - .packit.yaml

packages:
  netavark-fedora:
    pkg_tool: fedpkg
    specfile_path: rpm/netavark.spec
  netavark-centos:
    pkg_tool: centpkg
    specfile_path: rpm/netavark.spec
  netavark-eln:
    specfile_path: rpm/netavark.spec

srpm_build_deps:
  - cargo
  - make
  - openssl-devel

jobs:
  - job: copr_build
    trigger: pull_request
    packages: [netavark-fedora]
    #notifications: &copr_build_failure_notification
    #  failure_comment:
    #    message: "Ephemeral COPR build failed. @containers/packit-build please check."
    targets: &fedora_copr_targets
      - fedora-all-x86_64
      - fedora-all-aarch64
    enable_net: true

  - job: copr_build
    trigger: ignore
    packages: [netavark-eln]
    #notifications: &copr_build_failure_notification
    #  failure_comment:
    #    message: "Ephemeral COPR build failed. @containers/packit-build please check."
    targets:
      fedora-eln-x86_64:
        additional_repos:
          - "https://kojipkgs.fedoraproject.org/repos/eln-build/latest/x86_64/"
      fedora-eln-aarch64:
        additional_repos:
          - "https://kojipkgs.fedoraproject.org/repos/eln-build/latest/aarch64/"
    enable_net: true

  - job: copr_build
    trigger: pull_request
    packages: [netavark-centos]
    #notifications: *copr_build_failure_notification
    targets: &centos_copr_targets
      - centos-stream-9-x86_64
      - centos-stream-9-aarch64
      - centos-stream-10-x86_64
      - centos-stream-10-aarch64
    enable_net: true

  # Run on commit to main branch
  - job: copr_build
    trigger: commit
    packages: [netavark-fedora]
    notifications:
      failure_comment:
        message: "podman-next COPR build failed. @containers/packit-build please check."
    branch: main
    owner: rhcontainerbot
    project: podman-next
    enable_net: true

  # validate and unit tests
  # rpm independent and sufficient to run on only one env
  - job: tests
    trigger: pull_request
    packages: [netavark-fedora] # Include this else it will create multiple jobs
    skip_build: true
    targets:
      - fedora-latest-stable
    tmt_plan: "/plans/no-rpm"
    identifier: "no-rpm"

  - job: tests
    trigger: pull_request
    packages: [netavark-fedora]
      #notifications:
      #failure_comment:
      #  message: "TMT tests failed. @containers/packit-build please check."
    targets: *fedora_copr_targets
    tf_extra_params:
      environments:
        - artifacts:
          - type: repository-file
            id: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/repo/fedora-$releasever/rhcontainerbot-podman-next-fedora-$releasever.repo
    tmt_plan: "/plans/rpm"
    identifier: "rpm-fedora"

  - job: tests
    trigger: pull_request
    packages: [netavark-centos]
      #notifications:
      #failure_comment:
      #  message: "TMT tests failed. @containers/packit-build please check."
    targets: *centos_copr_targets
    tf_extra_params:
      environments:
        - artifacts:
          - type: repository-file
            id: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/repo/centos-stream-$releasever/rhcontainerbot-podman-next-centos-stream-$releasever.repo
    tmt_plan: "/plans/rpm"
    identifier: "rpm-centos"

  # Sync to Fedora
  - job: propose_downstream
    trigger: release
    packages: [netavark-fedora]
    update_release: false
    dist_git_branches:
      - fedora-all

  # Sync to CentOS Stream
  - job: propose_downstream
    trigger: release
    packages: [netavark-centos]
    update_release: false
    dist_git_branches:
      - c10s

  - job: koji_build
    trigger: commit
    packages: [netavark-fedora]
    sidetag_group: netavark-releases
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: koji_build
    packages: [netavark-fedora]
    sidetag_group: netavark-releases
    dependencies:
      - aardvark-dns
    dist_git_branches:
      - fedora-all
